# fly.toml app configuration file generated for asc-evm-listener on 2024-09-13T16:28:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'asc-evm-listener'
primary_region = 'ams'

[build]
dockerfile = "Dockerfile.staging"
ignorefile = ".dockerignore"

[deploy]
strategy = "rolling"
max_unavailable = 1

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
